# Generated by Django 4.0.6 on 2022-07-11 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='ride date')),
                ('distance', models.FloatField()),
                ('elevation', models.IntegerField()),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('avg_speed', models.FloatField(verbose_name='Average Speed')),
                ('description', models.TextField(max_length=300)),
            ],
        ),
    ]
